# Generated by Django 5.2.5 on 2025-09-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auther_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auther',
            old_name='NameError',
            new_name='name',
        ),
    ]
