# Generated by Django 5.2.5 on 2025-10-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
