# Generated by Django 5.2.5 on 2025-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtvs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='no descriptiond'),
        ),
    ]
